config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'passengers#home'

  resources :passengers do
      get :social, on: :member
      get :comment, on: :member
      post :print, on: :member
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  include PassengersHelper
  before_action :set_passenger, only: [:show, :edit, :update, :destroy, :social, :comment, :print]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end
  
  def social
    
  end
  
  def print
    uri = URI.parse("http://153.142.222.195:8888//jal_hackthon/print.php")
    http = Net::HTTP.new(uri.host, uri.port)
    
    form_data = {
      typeopt: @passenger.travel_type,
      txta: @passenger.comments
    }
    
    request = Net::HTTP.post_form(uri, form_data)
    
    render template: "passengers/index.html.erb"
  end
  
  def comment
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    @passenger.update(passenger_params)
    if params[:preview]
      render template: "passengers/show.html.erb"
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:flight, :seat, :name, :from, :destination, 
        :work, :hobby, :travel_type, :comments, :avatar, :fb, :linkedin, :source)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
    TRAVEL_TYPES = [OpenStruct.new(value: 1, label:"For Business"), 
                    OpenStruct.new(value: 2, label:"For Leisure"),
                    OpenStruct.new(value: 3, label:"For Family")]
    
    def travel_type_options
        TRAVEL_TYPES.collect{|i| [i.label, i.label]}
    end
    
    def travel_type_label(type)
        TRAVEL_TYPES.find{|i| i.value == type}.label
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JAL Fly Socially</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="fs-nav">
    <div class="nav-wrapper">
      <%=image_tag "jal-logo.jpg", class: "nav-logo"%>
      <%=link_to root_path, class: "nav-mobile right fs-home" do%>
        <i class="material-icons large">home</i>
      <%end%>
      <%=link_to :back, class: "nav-mobile right fs-home" do%>
        <i class="material-icons large">arrow_back</i>
      <%end%>
      </div>
  </nav>

  <br>
  <%= yield %>

</body>
</html>

app/views/passengers/_form.html.erb
<%= form_for(@passenger) do |f| %>
  <% if @passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% @passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight %><br>
    <%= f.text_field :flight %>
  </div>
  <div class="field">
    <%= f.label :seat %><br>
    <%= f.text_field :seat %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :work %><br>
    <%= f.text_field :work %>
  </div>
  <div class="field">
    <%= f.label :hobby %><br>
    <%= f.text_field :hobby %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :fb %><br>
    <%= f.text_field :fb %>
  </div>
  <div class="field">
    <%= f.label :linkedin %><br>
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passengers/_passenger.html.erb
<div class="container fs-card-box">
    <div class="row">
      <div class="card fs-card">
        <div class="card-image waves-effect waves-block waves-light">
            <%=image_tag passenger.avatar, class: "activator"%>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4 card-name">
              <%=passenger.name%>
              <i class="material-icons right">more_vert</i>
          </span>
          <p class="card-seat">
              <%=passenger.seat%>
          </p>
        </div>
        <div class="card-reveal">
          <span class="card-title activator grey-text text-darken-4 card-name">
              <%=passenger.name%>
              <i class="material-icons right">more_vert</i>
          </span>
          <p class="card-work">
              <%=passenger.work%>
          </p>
          <p>
            <i class="fa fa-facebook-official fa-3x"></i>
            <i class="fa fa-linkedin-square fa-3x"></i>
          </p>
            <p class="card-comment">
                "<%=passenger.comments%>"
            </p>
        </div>
      </div>
    </div>
</div>

app/views/passengers/comment.html.erb
<div class="container">
    <%= form_for(@passenger, validate: true) do |f| %>
        <div class="row">
          <div class="input-field col s8 offset-s2">
            <%=f.select :travel_type, options_for_select(travel_type_options, @passenger.travel_type)%>
            <%=f.label :travel_type, "Travel type"%>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s8 offset-s2">
            <%=f.text_area :comments, class: "comments materialize-textarea", rows: 2, maxlength: 80, length: 80%>
            <%=f.label :comments, "Comment about your trip"%>
          </div>
        </div>
        <div class="row">
            <div class="input-field col s8 offset-s4">
                <%=f.submit "Preview Tag", name: "preview", class: "waves-effect waves-light btn-large"%>
            </div>
        </div>
    <%end%>
</div>

<script>
  $(document).ready(function() {
    $('#passenger_travel_type').material_select();
  });
</script>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form' %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/home.html.erb
<div class="fs-large-button center-button">
    <div class="title-text">
        <i class="material-icons large">people</i>
        JAL Fly Socially Service
    </div>
    <%=link_to "Scan Your Ticket to Start", social_passenger_path(1), class: "waves-effect waves-light btn-large button"%>
</div>

app/views/passengers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s10 offset-s1">
      <h4>
        <i class="material-icons large">people</i>
        <span class="fs-circle-title">
          Fly Soially Circle for <%=Passenger.find(1).flight%>, <%=Passenger.find(1).destination%>
        </span>
      </h4>
    </div>
  </div>
  <% Passenger.all.each_slice(2) do |(i1, i2)|%>
    <div class="row">
      <div class="col s6">
        <%=render partial: "passengers/passenger", locals: {passenger: i1}%>
      </div>
      <div class="col s6">
        <%=render partial: "passengers/passenger", locals: {passenger: i2} if i2%>
      </div>
    </div>
  <% end%>
</div>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form' %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/show.html.erb
<div class="container">
    <div class="row">
        <div class="col s6 offset-s3">
            <div class="card-panel fs-card">
                <div class="fs-logo">
                    <i class="material-icons large md-light">people</i>
                        <div class="line white-text">
                            JAL Fly
                        </div>
                        <div class="line white-text">
                            Socially
                        </div>
                </div>
                <div class="info-box">
                    <div class="info">
                        To: <%=@passenger.destination%>
                    </div>
                    <div class="info">
                        Seat: <%=@passenger.seat%>
                    </div>
                </div>
            </div>
            <div class="card-panel fs-card">
                <div class="type-box">
                    <i class="material-icons medium">people</i>
                    <div class="type">
                        <%=@passenger.travel_type%>
                    </div>
                </div>
                <div class="comment">
                    <%=@passenger.comments%>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s4 offset-s4">
            <%=button_to print_passenger_path(1), class: "waves-effect waves-light btn-large fs-large-button" do%>
                <i class="material-icons large">print</i>
                Print
            <%end%>
        </div>
    </div>
</div>

app/views/passengers/social.html.erb
<div class="container">
    <div class="row passenger-info">
        <div class="col s4 offset-s3">
            Destination:
        </div>
        <div class="col s4">
            <%=@passenger.destination%>
        </div>
    </div>
    <div class="row passenger-info">
        <div class="col s4 offset-s3">
            Flight:
        </div>
        <div class="col s4">
            <%=@passenger.flight%>
        </div>
    </div>
    <div class="row passenger-info">
        <div class="col s4 offset-s3">
            Seat:
        </div>
        <div class="col s4">
            <%=@passenger.seat%>
        </div>
    </div>
    <div class="row passenger-info">
        <div class="col s4 offset-s3">
            Name:
        </div>
        <div class="col s4">
            <%=@passenger.name%>
        </div>
    </div>
    <div class="row passenger-info">
        <div class="col s6 offset-s4">
            <%=link_to comment_passenger_path(1), class: "waves-effect waves-light btn-large fs-large-button" do%>
                Tell us more
            <%end%>
        </div>
    </div>
</div>